app = 'twitter-to-discord'
primary_region = 'nrt'
swap_size_mb = 512

[build]

[env]
DATABASE_PATH = '/data'
FETCH_INTERVAL = '10'
FETCH_PAGE_INTERVAL = '10'

[[mounts]]
source = 'twitter_to_discord_mount'
destination = '/data'
initial_size = '1gb'
processes = ['app']

[[services]]
auto_stop_machines = 'stop'
auto_start_machines = false
min_machines_running = 1
ports = []
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
memory = '256mb'
